name: Hello World

on:
  push:
    branches:
      - dev

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: action/checkout@v3
        with: 
          repository: ${{ github.repository }}
          

      - name: Print Hello World
        run: echo ${{ github.repository }}
        
